### ISSUE TITLE
Regarding the results of SACN mentioned in your paper

### ISSUE THREAD

**Issue by xjzhao001** [malllabiisc/InteractE#1]
Hello, I want to ask about the results of SACN mentioned in your paper. Have you reproduced it? If it does, can you share your parameter settings? I searched a lot of information and tried to reproduce the results mentioned by the author in the paper, but they were far from reaching these results. Looking forward for your response, thank you!

**Comment by svjan5** [comment]
Hi @xjzhao001,
We also tried our best but could not reproduce SACN results. In the results, we have taken values directly from their paper. 

Thanks and regards,
