### ISSUE TITLE
How to set the parameters of reproducing WN18RR

### ISSUE THREAD

**Issue by xjzhao001** [malllabiisc/InteractE#2]
Hello, I am very interested in the method mentioned in your paper. Can you tell me all the parameters of reproducing WN18RR in detail? Looking forward to your reply, thank you!

**Comment by soumyasanyal** [comment]
Hi, we've mentioned the parameters for the different datasets in the `README` for the project. For WN18RR you can use this command - `python interacte.py --data WN18RR --batch 256 --train_strategy one_to_n --feat_drop 0.2 --hid_drop 0.3 --perm 4 --ker_sz 11 --lr 0.001`
