### ISSUE TITLE
Number of parameters

### ISSUE THREAD

**Issue by Demirrr** [malllabiisc/InteractE#3]
Hello,

I was wondering where the number of parameters of the InteractE on WN18RR, FB15k-237 and YAGO3-10 is reported somewhere.

Cheers

**Comment by soumyasanyal** [comment]
Hi Demirrr,

We do a comparison of the score functions of different embedding methods in Table 1 of our paper. We did not report the number of parameters for our best models. If you require them, it should be easy to run the given command to instantiate the model and compute the number of params before [this](https://github.com/malllabiisc/InteractE/blob/master/interacte.py#L202) line.

**Comment by svjan5** [comment]
The function to count the number of parameters is given here: 
https://gist.github.com/zackenton/12a86b6e0ff274b39608e40f4a412f2b
